stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main
    - master

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "docker pull $DOCKER_IMAGE"
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "docker stop frontend_container || true"
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "docker rm frontend_container || true"
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "docker run -d --name frontend_container -p 8501:8501 -e API_URL=$API_URL -e SHOW_FULL_FRONTEND=$SHOW_FULL_FRONTEND -e COLLECTION_NAME=$COLLECTION_NAME --restart always $DOCKER_IMAGE"
  only:
    - main
    - master
  environment:
    name: production
    url: https://it027065.uni-graz.at/frontend