[server]
baseUrlPath = "frontend"
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
base = "dark"
primaryColor = "#4B8BF4"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#252525"
textColor = "#FAFAFA"
font = "sans serif"
